apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fpm
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-fpm
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-fpm
    app.kubernetes.io/instance: {{ .Release.Name }}