apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-php
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-php
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-php
  replicas: {{ .Values.php.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-php
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Release.Name }}-php
          image: "{{ .Values.php.image }}:{{ .Values.php.tag }}"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: public-key
            - name: PRIVATE_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: private-key
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-name
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-password
            - name: ADMIN_FIRST_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: admin-firstname
            - name: ADMIN_LAST_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: admin-lastname
            - name: ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: admin-email
            - name: ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: admin-user
            - name: ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: admin-password
            - name: USE_REWRITES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: use-rewrites
            - name: ELASTIC_SEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: elasticsearch-host
            - name: ELASTIC_SEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: elasticsearch-port
            - name: SESSION_SAVE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: session-save
            - name: USE_SECURE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: use-secure
            - name: USE_SECURE_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: use-secure-admin
            - name: BACKEND_FRONTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: backend-frontname
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: base-url
            - name: BASE_URL_SECURE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: base-url-secure
            - name: TWO_FACTOR_AUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: two-factor-auth
          resources:
{{ toYaml .Values.resources | indent 12 }}