apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-nginx
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
      matchLabels:
          app.kubernetes.io/name: {{ .Release.Name }}-nginx
  replicas: {{ .Values.nginx.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-nginx
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Release.Name }}-nginx
          image: "{{ .Values.nginx.image }}:{{ .Values.nginx.tag }}"
          imagePullPolicy: {{ .Values.nginx.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: FPM_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: nginx-host
            - name: UPSTREAM_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: nginx-upstream
          resources:
{{ toYaml .Values.resources | indent 12 }}