name: Publish image

on:
  pull_request:
    branches:
      - master
      - development
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      # - name: Build the Docker images
      #   run: docker-compose build

      # - name: Run the Docker images
      #   run: docker-compose up -d

      # - name: Taking some sleep (for containers to come up)
      #   run: sleep 20
        
      # - name: Check if all containers are running
      #   run: docker ps

      - name: Log in to registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $(cut -d'/' -f1 <<< $GITHUB_REPOSITORY) --password-stdin

      # - name: Remove docker images
      #   run: docker-compose down